<?php
/**
 * Product
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Solifyn\Model;

use \ArrayAccess;
use \Solifyn\ObjectSerializer;

/**
 * Product Class Doc Comment
 *
 * @category Class
 * @description Represents a product item created under your business, containing core pricing, status, license behavior, subscription settings, and metadata details.
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Product implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Product';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'price' => 'float',
        'currency' => 'string',
        'description' => 'string',
        'status' => 'string',
        'image_url' => 'string',
        'tax_category' => 'string',
        'pricing_type' => 'string',
        'discount' => 'float',
        'has_license_key' => 'bool',
        'has_digital_delivery' => 'bool',
        'has_github_access' => 'bool',
        'github_repo' => 'string',
        'github_permission' => 'string',
        'has_discord_access' => 'bool',
        'discord_guild_id' => 'string',
        'discord_role_id' => 'string',
        'is_tax_inclusive' => 'bool',
        'billing_period' => 'int',
        'trial_period_days' => 'int',
        'expiration_days' => 'int',
        'statement_descriptor' => 'string',
        'pay_what_you_want' => 'bool',
        'metadata' => 'array<string,string>',
        'custom_fields' => 'object[]',
        'stock' => 'int',
        'activation_limit' => 'int',
        'is_listed' => 'bool',
        'is_free' => 'bool',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'is_permanently_deleted' => 'bool',
        'brand_id' => 'string',
        'digital_link' => 'string',
        'instructions' => 'string',
        'activation_message' => 'string',
        'expiry_hours' => 'int',
        'business_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'name' => null,
        'price' => null,
        'currency' => null,
        'description' => null,
        'status' => null,
        'image_url' => null,
        'tax_category' => null,
        'pricing_type' => null,
        'discount' => null,
        'has_license_key' => null,
        'has_digital_delivery' => null,
        'has_github_access' => null,
        'github_repo' => null,
        'github_permission' => null,
        'has_discord_access' => null,
        'discord_guild_id' => null,
        'discord_role_id' => null,
        'is_tax_inclusive' => null,
        'billing_period' => null,
        'trial_period_days' => null,
        'expiration_days' => null,
        'statement_descriptor' => null,
        'pay_what_you_want' => null,
        'metadata' => null,
        'custom_fields' => null,
        'stock' => null,
        'activation_limit' => null,
        'is_listed' => null,
        'is_free' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'is_permanently_deleted' => null,
        'brand_id' => null,
        'digital_link' => null,
        'instructions' => null,
        'activation_message' => null,
        'expiry_hours' => null,
        'business_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'price' => false,
        'currency' => false,
        'description' => false,
        'status' => false,
        'image_url' => false,
        'tax_category' => false,
        'pricing_type' => false,
        'discount' => false,
        'has_license_key' => false,
        'has_digital_delivery' => false,
        'has_github_access' => false,
        'github_repo' => false,
        'github_permission' => false,
        'has_discord_access' => false,
        'discord_guild_id' => false,
        'discord_role_id' => false,
        'is_tax_inclusive' => false,
        'billing_period' => false,
        'trial_period_days' => false,
        'expiration_days' => false,
        'statement_descriptor' => false,
        'pay_what_you_want' => false,
        'metadata' => false,
        'custom_fields' => false,
        'stock' => false,
        'activation_limit' => false,
        'is_listed' => false,
        'is_free' => false,
        'created_at' => false,
        'updated_at' => false,
        'is_permanently_deleted' => false,
        'brand_id' => false,
        'digital_link' => false,
        'instructions' => false,
        'activation_message' => false,
        'expiry_hours' => false,
        'business_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'price' => 'price',
        'currency' => 'currency',
        'description' => 'description',
        'status' => 'status',
        'image_url' => 'imageUrl',
        'tax_category' => 'taxCategory',
        'pricing_type' => 'pricingType',
        'discount' => 'discount',
        'has_license_key' => 'hasLicenseKey',
        'has_digital_delivery' => 'hasDigitalDelivery',
        'has_github_access' => 'hasGithubAccess',
        'github_repo' => 'githubRepo',
        'github_permission' => 'githubPermission',
        'has_discord_access' => 'hasDiscordAccess',
        'discord_guild_id' => 'discordGuildId',
        'discord_role_id' => 'discordRoleId',
        'is_tax_inclusive' => 'isTaxInclusive',
        'billing_period' => 'billingPeriod',
        'trial_period_days' => 'trialPeriodDays',
        'expiration_days' => 'expirationDays',
        'statement_descriptor' => 'statementDescriptor',
        'pay_what_you_want' => 'payWhatYouWant',
        'metadata' => 'metadata',
        'custom_fields' => 'customFields',
        'stock' => 'stock',
        'activation_limit' => 'activationLimit',
        'is_listed' => 'isListed',
        'is_free' => 'isFree',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'is_permanently_deleted' => 'isPermanentlyDeleted',
        'brand_id' => 'brandId',
        'digital_link' => 'digitalLink',
        'instructions' => 'instructions',
        'activation_message' => 'activationMessage',
        'expiry_hours' => 'expiryHours',
        'business_id' => 'businessId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'price' => 'setPrice',
        'currency' => 'setCurrency',
        'description' => 'setDescription',
        'status' => 'setStatus',
        'image_url' => 'setImageUrl',
        'tax_category' => 'setTaxCategory',
        'pricing_type' => 'setPricingType',
        'discount' => 'setDiscount',
        'has_license_key' => 'setHasLicenseKey',
        'has_digital_delivery' => 'setHasDigitalDelivery',
        'has_github_access' => 'setHasGithubAccess',
        'github_repo' => 'setGithubRepo',
        'github_permission' => 'setGithubPermission',
        'has_discord_access' => 'setHasDiscordAccess',
        'discord_guild_id' => 'setDiscordGuildId',
        'discord_role_id' => 'setDiscordRoleId',
        'is_tax_inclusive' => 'setIsTaxInclusive',
        'billing_period' => 'setBillingPeriod',
        'trial_period_days' => 'setTrialPeriodDays',
        'expiration_days' => 'setExpirationDays',
        'statement_descriptor' => 'setStatementDescriptor',
        'pay_what_you_want' => 'setPayWhatYouWant',
        'metadata' => 'setMetadata',
        'custom_fields' => 'setCustomFields',
        'stock' => 'setStock',
        'activation_limit' => 'setActivationLimit',
        'is_listed' => 'setIsListed',
        'is_free' => 'setIsFree',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'is_permanently_deleted' => 'setIsPermanentlyDeleted',
        'brand_id' => 'setBrandId',
        'digital_link' => 'setDigitalLink',
        'instructions' => 'setInstructions',
        'activation_message' => 'setActivationMessage',
        'expiry_hours' => 'setExpiryHours',
        'business_id' => 'setBusinessId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'price' => 'getPrice',
        'currency' => 'getCurrency',
        'description' => 'getDescription',
        'status' => 'getStatus',
        'image_url' => 'getImageUrl',
        'tax_category' => 'getTaxCategory',
        'pricing_type' => 'getPricingType',
        'discount' => 'getDiscount',
        'has_license_key' => 'getHasLicenseKey',
        'has_digital_delivery' => 'getHasDigitalDelivery',
        'has_github_access' => 'getHasGithubAccess',
        'github_repo' => 'getGithubRepo',
        'github_permission' => 'getGithubPermission',
        'has_discord_access' => 'getHasDiscordAccess',
        'discord_guild_id' => 'getDiscordGuildId',
        'discord_role_id' => 'getDiscordRoleId',
        'is_tax_inclusive' => 'getIsTaxInclusive',
        'billing_period' => 'getBillingPeriod',
        'trial_period_days' => 'getTrialPeriodDays',
        'expiration_days' => 'getExpirationDays',
        'statement_descriptor' => 'getStatementDescriptor',
        'pay_what_you_want' => 'getPayWhatYouWant',
        'metadata' => 'getMetadata',
        'custom_fields' => 'getCustomFields',
        'stock' => 'getStock',
        'activation_limit' => 'getActivationLimit',
        'is_listed' => 'getIsListed',
        'is_free' => 'getIsFree',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'is_permanently_deleted' => 'getIsPermanentlyDeleted',
        'brand_id' => 'getBrandId',
        'digital_link' => 'getDigitalLink',
        'instructions' => 'getInstructions',
        'activation_message' => 'getActivationMessage',
        'expiry_hours' => 'getExpiryHours',
        'business_id' => 'getBusinessId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TAX_CATEGORY_DIGITAL_PRODUCTS = 'digital_products';
    public const TAX_CATEGORY_SAAS = 'saas';
    public const TAX_CATEGORY_PHYSICAL_PRODUCTS = 'physical_products';
    public const TAX_CATEGORY_SERVICE = 'service';
    public const PRICING_TYPE_USAGE_BASED = 'usage_based';
    public const PRICING_TYPE_ONE_TIME = 'one_time';
    public const PRICING_TYPE_RENEWAL = 'renewal';
    public const GITHUB_PERMISSION_PULL = 'pull';
    public const GITHUB_PERMISSION_TRIAGE = 'triage';
    public const GITHUB_PERMISSION_PUSH = 'push';
    public const GITHUB_PERMISSION_MAINTAIN = 'maintain';
    public const GITHUB_PERMISSION_ADMIN = 'admin';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTaxCategoryAllowableValues()
    {
        return [
            self::TAX_CATEGORY_DIGITAL_PRODUCTS,
            self::TAX_CATEGORY_SAAS,
            self::TAX_CATEGORY_PHYSICAL_PRODUCTS,
            self::TAX_CATEGORY_SERVICE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPricingTypeAllowableValues()
    {
        return [
            self::PRICING_TYPE_USAGE_BASED,
            self::PRICING_TYPE_ONE_TIME,
            self::PRICING_TYPE_RENEWAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGithubPermissionAllowableValues()
    {
        return [
            self::GITHUB_PERMISSION_PULL,
            self::GITHUB_PERMISSION_TRIAGE,
            self::GITHUB_PERMISSION_PUSH,
            self::GITHUB_PERMISSION_MAINTAIN,
            self::GITHUB_PERMISSION_ADMIN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('tax_category', $data ?? [], null);
        $this->setIfExists('pricing_type', $data ?? [], null);
        $this->setIfExists('discount', $data ?? [], null);
        $this->setIfExists('has_license_key', $data ?? [], null);
        $this->setIfExists('has_digital_delivery', $data ?? [], null);
        $this->setIfExists('has_github_access', $data ?? [], null);
        $this->setIfExists('github_repo', $data ?? [], null);
        $this->setIfExists('github_permission', $data ?? [], null);
        $this->setIfExists('has_discord_access', $data ?? [], null);
        $this->setIfExists('discord_guild_id', $data ?? [], null);
        $this->setIfExists('discord_role_id', $data ?? [], null);
        $this->setIfExists('is_tax_inclusive', $data ?? [], null);
        $this->setIfExists('billing_period', $data ?? [], null);
        $this->setIfExists('trial_period_days', $data ?? [], null);
        $this->setIfExists('expiration_days', $data ?? [], null);
        $this->setIfExists('statement_descriptor', $data ?? [], null);
        $this->setIfExists('pay_what_you_want', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('custom_fields', $data ?? [], null);
        $this->setIfExists('stock', $data ?? [], null);
        $this->setIfExists('activation_limit', $data ?? [], null);
        $this->setIfExists('is_listed', $data ?? [], null);
        $this->setIfExists('is_free', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('is_permanently_deleted', $data ?? [], null);
        $this->setIfExists('brand_id', $data ?? [], null);
        $this->setIfExists('digital_link', $data ?? [], null);
        $this->setIfExists('instructions', $data ?? [], null);
        $this->setIfExists('activation_message', $data ?? [], null);
        $this->setIfExists('expiry_hours', $data ?? [], null);
        $this->setIfExists('business_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['image_url'] === null) {
            $invalidProperties[] = "'image_url' can't be null";
        }
        if ($this->container['tax_category'] === null) {
            $invalidProperties[] = "'tax_category' can't be null";
        }
        $allowedValues = $this->getTaxCategoryAllowableValues();
        if (!is_null($this->container['tax_category']) && !in_array($this->container['tax_category'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tax_category', must be one of '%s'",
                $this->container['tax_category'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['pricing_type'] === null) {
            $invalidProperties[] = "'pricing_type' can't be null";
        }
        $allowedValues = $this->getPricingTypeAllowableValues();
        if (!is_null($this->container['pricing_type']) && !in_array($this->container['pricing_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'pricing_type', must be one of '%s'",
                $this->container['pricing_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['discount'] === null) {
            $invalidProperties[] = "'discount' can't be null";
        }
        if ($this->container['has_license_key'] === null) {
            $invalidProperties[] = "'has_license_key' can't be null";
        }
        if ($this->container['has_digital_delivery'] === null) {
            $invalidProperties[] = "'has_digital_delivery' can't be null";
        }
        if ($this->container['has_github_access'] === null) {
            $invalidProperties[] = "'has_github_access' can't be null";
        }
        if ($this->container['github_repo'] === null) {
            $invalidProperties[] = "'github_repo' can't be null";
        }
        if ($this->container['github_permission'] === null) {
            $invalidProperties[] = "'github_permission' can't be null";
        }
        $allowedValues = $this->getGithubPermissionAllowableValues();
        if (!is_null($this->container['github_permission']) && !in_array($this->container['github_permission'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'github_permission', must be one of '%s'",
                $this->container['github_permission'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['has_discord_access'] === null) {
            $invalidProperties[] = "'has_discord_access' can't be null";
        }
        if ($this->container['discord_guild_id'] === null) {
            $invalidProperties[] = "'discord_guild_id' can't be null";
        }
        if ($this->container['discord_role_id'] === null) {
            $invalidProperties[] = "'discord_role_id' can't be null";
        }
        if ($this->container['is_tax_inclusive'] === null) {
            $invalidProperties[] = "'is_tax_inclusive' can't be null";
        }
        if ($this->container['billing_period'] === null) {
            $invalidProperties[] = "'billing_period' can't be null";
        }
        if ($this->container['trial_period_days'] === null) {
            $invalidProperties[] = "'trial_period_days' can't be null";
        }
        if ($this->container['expiration_days'] === null) {
            $invalidProperties[] = "'expiration_days' can't be null";
        }
        if ($this->container['statement_descriptor'] === null) {
            $invalidProperties[] = "'statement_descriptor' can't be null";
        }
        if ($this->container['pay_what_you_want'] === null) {
            $invalidProperties[] = "'pay_what_you_want' can't be null";
        }
        if ($this->container['metadata'] === null) {
            $invalidProperties[] = "'metadata' can't be null";
        }
        if ($this->container['custom_fields'] === null) {
            $invalidProperties[] = "'custom_fields' can't be null";
        }
        if ($this->container['stock'] === null) {
            $invalidProperties[] = "'stock' can't be null";
        }
        if ($this->container['activation_limit'] === null) {
            $invalidProperties[] = "'activation_limit' can't be null";
        }
        if ($this->container['is_listed'] === null) {
            $invalidProperties[] = "'is_listed' can't be null";
        }
        if ($this->container['is_free'] === null) {
            $invalidProperties[] = "'is_free' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        if ($this->container['is_permanently_deleted'] === null) {
            $invalidProperties[] = "'is_permanently_deleted' can't be null";
        }
        if ($this->container['brand_id'] === null) {
            $invalidProperties[] = "'brand_id' can't be null";
        }
        if ($this->container['digital_link'] === null) {
            $invalidProperties[] = "'digital_link' can't be null";
        }
        if ($this->container['instructions'] === null) {
            $invalidProperties[] = "'instructions' can't be null";
        }
        if ($this->container['activation_message'] === null) {
            $invalidProperties[] = "'activation_message' can't be null";
        }
        if ($this->container['expiry_hours'] === null) {
            $invalidProperties[] = "'expiry_hours' can't be null";
        }
        if ($this->container['business_id'] === null) {
            $invalidProperties[] = "'business_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The unique identifier (ID) of the product.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The display name of the product.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets price
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param float $price The price amount of the product (e.g. 29.00).
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency The three-letter ISO currency code (e.g. USD, VND, EUR).
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description A comprehensive rich text description of the product.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The lifecycle status of the product (e.g. ACTIVE, ARCHIVED).
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string $image_url URL of the product cover image.
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            throw new \InvalidArgumentException('non-nullable image_url cannot be null');
        }
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets tax_category
     *
     * @return string
     */
    public function getTaxCategory()
    {
        return $this->container['tax_category'];
    }

    /**
     * Sets tax_category
     *
     * @param string $tax_category The tax classification for the product.
     *
     * @return self
     */
    public function setTaxCategory($tax_category)
    {
        if (is_null($tax_category)) {
            throw new \InvalidArgumentException('non-nullable tax_category cannot be null');
        }
        $allowedValues = $this->getTaxCategoryAllowableValues();
        if (!in_array($tax_category, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tax_category', must be one of '%s'",
                    $tax_category,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tax_category'] = $tax_category;

        return $this;
    }

    /**
     * Gets pricing_type
     *
     * @return string
     */
    public function getPricingType()
    {
        return $this->container['pricing_type'];
    }

    /**
     * Sets pricing_type
     *
     * @param string $pricing_type Pricing model of the product.
     *
     * @return self
     */
    public function setPricingType($pricing_type)
    {
        if (is_null($pricing_type)) {
            throw new \InvalidArgumentException('non-nullable pricing_type cannot be null');
        }
        $allowedValues = $this->getPricingTypeAllowableValues();
        if (!in_array($pricing_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'pricing_type', must be one of '%s'",
                    $pricing_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['pricing_type'] = $pricing_type;

        return $this;
    }

    /**
     * Gets discount
     *
     * @return float
     */
    public function getDiscount()
    {
        return $this->container['discount'];
    }

    /**
     * Sets discount
     *
     * @param float $discount Discount value as a percentage or fixed amount.
     *
     * @return self
     */
    public function setDiscount($discount)
    {
        if (is_null($discount)) {
            throw new \InvalidArgumentException('non-nullable discount cannot be null');
        }
        $this->container['discount'] = $discount;

        return $this;
    }

    /**
     * Gets has_license_key
     *
     * @return bool
     */
    public function getHasLicenseKey()
    {
        return $this->container['has_license_key'];
    }

    /**
     * Sets has_license_key
     *
     * @param bool $has_license_key Indicates if the product issues a cryptographically secure software license key upon checkout completion.
     *
     * @return self
     */
    public function setHasLicenseKey($has_license_key)
    {
        if (is_null($has_license_key)) {
            throw new \InvalidArgumentException('non-nullable has_license_key cannot be null');
        }
        $this->container['has_license_key'] = $has_license_key;

        return $this;
    }

    /**
     * Gets has_digital_delivery
     *
     * @return bool
     */
    public function getHasDigitalDelivery()
    {
        return $this->container['has_digital_delivery'];
    }

    /**
     * Sets has_digital_delivery
     *
     * @param bool $has_digital_delivery Whether the product includes digital file downloads upon purchase.
     *
     * @return self
     */
    public function setHasDigitalDelivery($has_digital_delivery)
    {
        if (is_null($has_digital_delivery)) {
            throw new \InvalidArgumentException('non-nullable has_digital_delivery cannot be null');
        }
        $this->container['has_digital_delivery'] = $has_digital_delivery;

        return $this;
    }

    /**
     * Gets has_github_access
     *
     * @return bool
     */
    public function getHasGithubAccess()
    {
        return $this->container['has_github_access'];
    }

    /**
     * Sets has_github_access
     *
     * @param bool $has_github_access Whether the product includes GitHub repository access.
     *
     * @return self
     */
    public function setHasGithubAccess($has_github_access)
    {
        if (is_null($has_github_access)) {
            throw new \InvalidArgumentException('non-nullable has_github_access cannot be null');
        }
        $this->container['has_github_access'] = $has_github_access;

        return $this;
    }

    /**
     * Gets github_repo
     *
     * @return string
     */
    public function getGithubRepo()
    {
        return $this->container['github_repo'];
    }

    /**
     * Sets github_repo
     *
     * @param string $github_repo GitHub repository to grant access to (format: owner/repo).
     *
     * @return self
     */
    public function setGithubRepo($github_repo)
    {
        if (is_null($github_repo)) {
            throw new \InvalidArgumentException('non-nullable github_repo cannot be null');
        }
        $this->container['github_repo'] = $github_repo;

        return $this;
    }

    /**
     * Gets github_permission
     *
     * @return string
     */
    public function getGithubPermission()
    {
        return $this->container['github_permission'];
    }

    /**
     * Sets github_permission
     *
     * @param string $github_permission GitHub collaborator permission level.
     *
     * @return self
     */
    public function setGithubPermission($github_permission)
    {
        if (is_null($github_permission)) {
            throw new \InvalidArgumentException('non-nullable github_permission cannot be null');
        }
        $allowedValues = $this->getGithubPermissionAllowableValues();
        if (!in_array($github_permission, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'github_permission', must be one of '%s'",
                    $github_permission,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['github_permission'] = $github_permission;

        return $this;
    }

    /**
     * Gets has_discord_access
     *
     * @return bool
     */
    public function getHasDiscordAccess()
    {
        return $this->container['has_discord_access'];
    }

    /**
     * Sets has_discord_access
     *
     * @param bool $has_discord_access Whether the product includes Discord role access.
     *
     * @return self
     */
    public function setHasDiscordAccess($has_discord_access)
    {
        if (is_null($has_discord_access)) {
            throw new \InvalidArgumentException('non-nullable has_discord_access cannot be null');
        }
        $this->container['has_discord_access'] = $has_discord_access;

        return $this;
    }

    /**
     * Gets discord_guild_id
     *
     * @return string
     */
    public function getDiscordGuildId()
    {
        return $this->container['discord_guild_id'];
    }

    /**
     * Sets discord_guild_id
     *
     * @param string $discord_guild_id Discord Guild (Server) ID to grant access to.
     *
     * @return self
     */
    public function setDiscordGuildId($discord_guild_id)
    {
        if (is_null($discord_guild_id)) {
            throw new \InvalidArgumentException('non-nullable discord_guild_id cannot be null');
        }
        $this->container['discord_guild_id'] = $discord_guild_id;

        return $this;
    }

    /**
     * Gets discord_role_id
     *
     * @return string
     */
    public function getDiscordRoleId()
    {
        return $this->container['discord_role_id'];
    }

    /**
     * Sets discord_role_id
     *
     * @param string $discord_role_id Discord Role ID to assign to the user.
     *
     * @return self
     */
    public function setDiscordRoleId($discord_role_id)
    {
        if (is_null($discord_role_id)) {
            throw new \InvalidArgumentException('non-nullable discord_role_id cannot be null');
        }
        $this->container['discord_role_id'] = $discord_role_id;

        return $this;
    }

    /**
     * Gets is_tax_inclusive
     *
     * @return bool
     */
    public function getIsTaxInclusive()
    {
        return $this->container['is_tax_inclusive'];
    }

    /**
     * Sets is_tax_inclusive
     *
     * @param bool $is_tax_inclusive Whether the product price already includes applicable sales taxes.
     *
     * @return self
     */
    public function setIsTaxInclusive($is_tax_inclusive)
    {
        if (is_null($is_tax_inclusive)) {
            throw new \InvalidArgumentException('non-nullable is_tax_inclusive cannot be null');
        }
        $this->container['is_tax_inclusive'] = $is_tax_inclusive;

        return $this;
    }

    /**
     * Gets billing_period
     *
     * @return int
     */
    public function getBillingPeriod()
    {
        return $this->container['billing_period'];
    }

    /**
     * Sets billing_period
     *
     * @param int $billing_period The subscription billing cycle interval in days (for subscription products).
     *
     * @return self
     */
    public function setBillingPeriod($billing_period)
    {
        if (is_null($billing_period)) {
            throw new \InvalidArgumentException('non-nullable billing_period cannot be null');
        }
        $this->container['billing_period'] = $billing_period;

        return $this;
    }

    /**
     * Gets trial_period_days
     *
     * @return int
     */
    public function getTrialPeriodDays()
    {
        return $this->container['trial_period_days'];
    }

    /**
     * Sets trial_period_days
     *
     * @param int $trial_period_days Trial duration in days for subscription products.
     *
     * @return self
     */
    public function setTrialPeriodDays($trial_period_days)
    {
        if (is_null($trial_period_days)) {
            throw new \InvalidArgumentException('non-nullable trial_period_days cannot be null');
        }
        $this->container['trial_period_days'] = $trial_period_days;

        return $this;
    }

    /**
     * Gets expiration_days
     *
     * @return int
     */
    public function getExpirationDays()
    {
        return $this->container['expiration_days'];
    }

    /**
     * Sets expiration_days
     *
     * @param int $expiration_days Automatic expiration period in days for the subscription entitlement.
     *
     * @return self
     */
    public function setExpirationDays($expiration_days)
    {
        if (is_null($expiration_days)) {
            throw new \InvalidArgumentException('non-nullable expiration_days cannot be null');
        }
        $this->container['expiration_days'] = $expiration_days;

        return $this;
    }

    /**
     * Gets statement_descriptor
     *
     * @return string
     */
    public function getStatementDescriptor()
    {
        return $this->container['statement_descriptor'];
    }

    /**
     * Sets statement_descriptor
     *
     * @param string $statement_descriptor Custom text displayed on customer credit card statements for purchases of this product.
     *
     * @return self
     */
    public function setStatementDescriptor($statement_descriptor)
    {
        if (is_null($statement_descriptor)) {
            throw new \InvalidArgumentException('non-nullable statement_descriptor cannot be null');
        }
        $this->container['statement_descriptor'] = $statement_descriptor;

        return $this;
    }

    /**
     * Gets pay_what_you_want
     *
     * @return bool
     */
    public function getPayWhatYouWant()
    {
        return $this->container['pay_what_you_want'];
    }

    /**
     * Sets pay_what_you_want
     *
     * @param bool $pay_what_you_want Indicates if customers are allowed to enter a custom pricing amount at checkout.
     *
     * @return self
     */
    public function setPayWhatYouWant($pay_what_you_want)
    {
        if (is_null($pay_what_you_want)) {
            throw new \InvalidArgumentException('non-nullable pay_what_you_want cannot be null');
        }
        $this->container['pay_what_you_want'] = $pay_what_you_want;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string> $metadata Custom developer metadata key-value pairs associated with the product.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object[]
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object[] $custom_fields Custom form field questions to ask the customer during checkout.
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        if (is_null($custom_fields)) {
            throw new \InvalidArgumentException('non-nullable custom_fields cannot be null');
        }
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets stock
     *
     * @return int
     */
    public function getStock()
    {
        return $this->container['stock'];
    }

    /**
     * Sets stock
     *
     * @param int $stock Available stock quantity, or null for unlimited inventory.
     *
     * @return self
     */
    public function setStock($stock)
    {
        if (is_null($stock)) {
            throw new \InvalidArgumentException('non-nullable stock cannot be null');
        }
        $this->container['stock'] = $stock;

        return $this;
    }

    /**
     * Gets activation_limit
     *
     * @return int
     */
    public function getActivationLimit()
    {
        return $this->container['activation_limit'];
    }

    /**
     * Sets activation_limit
     *
     * @param int $activation_limit Maximum number of simultaneous active instances/devices allowed per issued license key (applicable if hasLicenseKey is true).
     *
     * @return self
     */
    public function setActivationLimit($activation_limit)
    {
        if (is_null($activation_limit)) {
            throw new \InvalidArgumentException('non-nullable activation_limit cannot be null');
        }
        $this->container['activation_limit'] = $activation_limit;

        return $this;
    }

    /**
     * Gets is_listed
     *
     * @return bool
     */
    public function getIsListed()
    {
        return $this->container['is_listed'];
    }

    /**
     * Sets is_listed
     *
     * @param bool $is_listed Defines if the product is listed publicly on the merchant's storefront template.
     *
     * @return self
     */
    public function setIsListed($is_listed)
    {
        if (is_null($is_listed)) {
            throw new \InvalidArgumentException('non-nullable is_listed cannot be null');
        }
        $this->container['is_listed'] = $is_listed;

        return $this;
    }

    /**
     * Gets is_free
     *
     * @return bool
     */
    public function getIsFree()
    {
        return $this->container['is_free'];
    }

    /**
     * Sets is_free
     *
     * @param bool $is_free Whether the product is free.
     *
     * @return self
     */
    public function setIsFree($is_free)
    {
        if (is_null($is_free)) {
            throw new \InvalidArgumentException('non-nullable is_free cannot be null');
        }
        $this->container['is_free'] = $is_free;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at Timestamp indicating exactly when the product was created.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at Timestamp indicating when the product was last modified.
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets is_permanently_deleted
     *
     * @return bool
     */
    public function getIsPermanentlyDeleted()
    {
        return $this->container['is_permanently_deleted'];
    }

    /**
     * Sets is_permanently_deleted
     *
     * @param bool $is_permanently_deleted Indicates if the product has been permanently deleted.
     *
     * @return self
     */
    public function setIsPermanentlyDeleted($is_permanently_deleted)
    {
        if (is_null($is_permanently_deleted)) {
            throw new \InvalidArgumentException('non-nullable is_permanently_deleted cannot be null');
        }
        $this->container['is_permanently_deleted'] = $is_permanently_deleted;

        return $this;
    }

    /**
     * Gets brand_id
     *
     * @return string
     */
    public function getBrandId()
    {
        return $this->container['brand_id'];
    }

    /**
     * Sets brand_id
     *
     * @param string $brand_id Optional brand identifier.
     *
     * @return self
     */
    public function setBrandId($brand_id)
    {
        if (is_null($brand_id)) {
            throw new \InvalidArgumentException('non-nullable brand_id cannot be null');
        }
        $this->container['brand_id'] = $brand_id;

        return $this;
    }

    /**
     * Gets digital_link
     *
     * @return string
     */
    public function getDigitalLink()
    {
        return $this->container['digital_link'];
    }

    /**
     * Sets digital_link
     *
     * @param string $digital_link Secure link for digital delivery.
     *
     * @return self
     */
    public function setDigitalLink($digital_link)
    {
        if (is_null($digital_link)) {
            throw new \InvalidArgumentException('non-nullable digital_link cannot be null');
        }
        $this->container['digital_link'] = $digital_link;

        return $this;
    }

    /**
     * Gets instructions
     *
     * @return string
     */
    public function getInstructions()
    {
        return $this->container['instructions'];
    }

    /**
     * Sets instructions
     *
     * @param string $instructions Special instructions provided upon purchase.
     *
     * @return self
     */
    public function setInstructions($instructions)
    {
        if (is_null($instructions)) {
            throw new \InvalidArgumentException('non-nullable instructions cannot be null');
        }
        $this->container['instructions'] = $instructions;

        return $this;
    }

    /**
     * Gets activation_message
     *
     * @return string
     */
    public function getActivationMessage()
    {
        return $this->container['activation_message'];
    }

    /**
     * Sets activation_message
     *
     * @param string $activation_message Custom message displayed when a license key is activated.
     *
     * @return self
     */
    public function setActivationMessage($activation_message)
    {
        if (is_null($activation_message)) {
            throw new \InvalidArgumentException('non-nullable activation_message cannot be null');
        }
        $this->container['activation_message'] = $activation_message;

        return $this;
    }

    /**
     * Gets expiry_hours
     *
     * @return int
     */
    public function getExpiryHours()
    {
        return $this->container['expiry_hours'];
    }

    /**
     * Sets expiry_hours
     *
     * @param int $expiry_hours Number of hours until the license key expires.
     *
     * @return self
     */
    public function setExpiryHours($expiry_hours)
    {
        if (is_null($expiry_hours)) {
            throw new \InvalidArgumentException('non-nullable expiry_hours cannot be null');
        }
        $this->container['expiry_hours'] = $expiry_hours;

        return $this;
    }

    /**
     * Gets business_id
     *
     * @return string
     */
    public function getBusinessId()
    {
        return $this->container['business_id'];
    }

    /**
     * Sets business_id
     *
     * @param string $business_id The unique identifier of the business owning this product.
     *
     * @return self
     */
    public function setBusinessId($business_id)
    {
        if (is_null($business_id)) {
            throw new \InvalidArgumentException('non-nullable business_id cannot be null');
        }
        $this->container['business_id'] = $business_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


