<?php
/**
 * ProductAddOnsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Solifyn\Test\Api;

use \Solifyn\Configuration;
use \Solifyn\ApiException;
use \Solifyn\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductAddOnsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Solifyn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductAddOnsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productsCreateAddon
     *
     * Create Product Add-on.
     *
     */
    public function testProductsCreateAddon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsDeleteAddon
     *
     * Delete Product Add-on.
     *
     */
    public function testProductsDeleteAddon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsGetAddon
     *
     * Retrieve Product Add-on.
     *
     */
    public function testProductsGetAddon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsListAddons
     *
     * List Product Add-ons.
     *
     */
    public function testProductsListAddons()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsListAllAddons
     *
     * List All Add-ons.
     *
     */
    public function testProductsListAllAddons()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsUpdateAddon
     *
     * Update Product Add-on.
     *
     */
    public function testProductsUpdateAddon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
